services:
  cache:
    image: redis:6
    restart: ${RESTART_POLICY:-no}

  directus:
    depends_on:
      - cache
    environment:
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
